### ISSUE TITLE
Switcher doesn't switch

### ISSUE THREAD

**Issue by savchenko** [ErikReider/SwayFloatingSwitcher#3]
In continuation of https://github.com/ErikReider/SwayFloatingSwitcher/issues/2,

```sh
ps ax | grep 'swayfloatingswitcher'
569641 pts/0    Sl+    0:00 ./swayfloatingswitcher
```

In Sway config:
```conf
bindsym Alt+Tab exec swayfloatingswitcher-client --next
bindsym Alt+Shift+Tab exec swayfloatingswitcher-client --previous
```

Also:
```gdb
run --next
Starting program: /home/user/code/SwayFloatingSwitcher/build/src/swayfloatingswitcher --next
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff56c7700 (LWP 571887)]
[New Thread 0x7ffff4ec6700 (LWP 571888)]
[New Thread 0x7fffeffff700 (LWP 571889)]
[New Thread 0x7fffef7fe700 (LWP 571890)]
Could not aquire "org.erikreider.swayfloatingswitcher" name
[Thread 0x7ffff4ec6700 (LWP 571888) exited]
^C
Thread 1 "swayfloatingswi" received signal SIGINT, Interrupt.
0x00007ffff71853ff in __GI___poll (fds=0x5555555e63a0, nfds=2, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
```

**Comment by ErikReider** [comment]
Only one instance of swayfloatingswitcher can be running at a time (per user). 

I'm not sure if the GitHub app is cutting some of the post off or not so I'll check again tomorrow

**Comment by savchenko** [comment]
> Only one instance of swayfloatingswitcher can be running at a time (per user).

I have only one instance running as can be seen from the first snippet.

> I'm not sure if the GitHub app is cutting some of the post off or not so I'll check again tomorrow

Quite likely :) Enjoy the rest!

**Comment by ErikReider** [comment]
Hmmm... What session dbus services are running? You can use Gnomes DFeet or Qts QDBusViewer :)

**Comment by savchenko** [comment]
```sh
$ sudo ps ax | grep dbus # unrelated stuff is manually trimmed
    804 ?        Ss     0:08 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
   1491 ?        Ss     0:01 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
```

**Comment by ErikReider** [comment]
I was referring to which dbus objects are you running. If `swayfloatingswitcher` is there, the application is running in the background

![image](https://user-images.githubusercontent.com/35975961/141854518-68eefcaa-1c27-4f7d-b3fc-79f6b1c12554.png)

**Comment by savchenko** [comment]
Can confirm, it's there:
```sh
qdbus | grep -C1 sway
:1.710
 org.erikreider.swayfloatingswitcher
```

**Edit**

![image](https://user-images.githubusercontent.com/300146/141855420-0cd44049-d6aa-42bb-a81d-2c502ce8e1fa.png)

**Comment by ErikReider** [comment]
So then the application should be up and running in the background

**Comment by savchenko** [comment]
> So then the application should be up and running in the background

It does. Added screenshot from the `d-feet` above. Anything else you might find helpful?

**Comment by ErikReider** [comment]
Everything looks good. Try running `killall swayfloatingswitcher; swayfloatingswitcher`

**Comment by savchenko** [comment]
As expected, `swayfloatingswitcher: no process found`. Meaning I don't have one lingering on the background. I have also checked if it is affected by `~/.config/gtk-3.0/gtk.css` - not the case.

Can you post a screenshot how working `swayfloatingswitcher` looks like?

**Comment by ErikReider** [comment]
It'll only appear if there's a floating window in the focused workspace on the focused monitor

![image](https://user-images.githubusercontent.com/35975961/141856302-d896ef53-1157-41bb-b002-cd7300d5b358.png)

**Comment by savchenko** [comment]
Good point of reference. Created a couple of floating windows of `foot`, re-launched server and executed client manually:
```sh
./swayfloatingswitcher --next
Could not aquire "org.erikreider.swayfloatingswitcher" name
```

:-/

**Comment by ErikReider** [comment]
Try running `swayfloatingswitcher-client --next` instead

**Comment by savchenko** [comment]
That was one unfortunate typo!

![image](https://user-images.githubusercontent.com/300146/141857466-a8dc7ee4-ac2a-4279-8b6e-b7298316dd1c.png)

Let's close the issue?

**Comment by ErikReider** [comment]
Great! That happens to me all the time 😅
