### ISSUE TITLE
Navigate using arrow keys

### ISSUE THREAD

**Issue by asjur** [ErikReider/SwayFloatingSwitcher#6]
Would it be possible that once you open up the switcher with alt+tab, to navigate it using the arrow keys?

If you have multiple windows open I find it much easier to just left or right arrow to navigate than to continue to cycle until I go back around to the window that I wanted to select.

**Comment by ErikReider** [comment]
You mean while still holding down the left alt?

**Comment by asjur** [comment]
Correct

**Comment by ErikReider** [comment]
Ok cool. I'll check it out :)

**Comment by ErikReider** [comment]
4f02259af507cc68e5eba9bbdf4b8b4ebf5c5d14 Fixes this :)
